<strong>El mundo debería estar liberado de que se le exijan a uno documentos</strong><br><br>
Por Pierre-Marc René<br><br><br>
Enrique Guarner vivió solamente seis años en España debido a que su padre, Vicente, militar de carrera y compañero de clase de Francisco Franco desde la adolescencia, se fue a combatir a África. Al estallar la Guerra Civil, el padre se alió a los republicanos y se volvió enemigo de Franco.<br><br>
“Mi padre tuvo bastante importancia en el desarrollo de la Guerra Civil, estuvo en diversas batallas, prácticamente era el que comandaba todo el frente de Aragón en aquella época y mandaba 48 mil hombres”, relata el hombre de 87 años.<br><br>
Al terminar la guerra, la familia Guarner tuvo que salir de España y llegó a Casablanca, en la parte francesa de Marruecos, donde vivió entre 1938 y 1941, hasta la invasión de Francia.<br><br>
Para evitar la deportación de su padre a España, la familia Guarner huyó de nueva cuenta. A petición de su madre, Enrique puso todo lo que pudo en un baúl que conserva todavía y subió, junto con su familia al barco portugués “Quanza” con rumbo a México.<br><br>
En ese barco se encontraba el presidente de la República Española, Niceto Alcalá Zamora, quien se quedó en tercera clase a pesar de que el capitán le ofreció un camarote de primera. La travesía hasta Veracruz duró 17 días. Llegaron el 19 de noviembre de 1941. La idea era ir a Argentina al igual que Alcalá Zamora, quien sí continuó su camino hasta Buenos Aires.<br><br>
En Veracruz, la familia Guarner tomó un automóvil hasta Ciudad de México.<br><br>
“Comimos en Xalapa, quien acompañaba a mi padre decidió que deberíamos probar la comida mexicana. Pidió mole, a mi hermana y a mí se nos ofreció “Coca-Cola”, que a mí me supo a petróleo, el mole era muy picante. Tuve la sensación de que en México me moriría de hambre”, comenta riéndose.<br><br>
Al llegar a la Ciudad de México, la familia se instaló en una pensión en Bucareli, en el Centro. A pocos metros había un desfile deportivo en Avenida Juárez.<br><br>
“Mi mamá, que se sentía muy elegante e importante, quedó horrorizada, porque se tiraban naranjas. Era el populacho el que estaba presente en ese lugar, fue el primer contacto que tuve con México derivado de ser refugiado”, señala.<br><br>
Otro tema impactante al principio fue el cine, porque las películas en Casablanca estaban dobladas al francés, su primer idioma. En México, las películas estaban en inglés y llevaban subtítulos y no le daba tiempo de leerlos.<br><br>
También le costó entender el significado de las expresiones mexicanas.<br><br>
“Había un letrero muy grande que decía ‘Ay Jalisco no te rajes’, no entendía por qué se había rajado alguien que se llamaba Jalisco. Después supe que era una película de Jorge Negrete y que ‘rajarse’ era ‘acobardarse’”, explica.<br><br>
Para Enrique, el contacto real con los mexicanos lo tuvo hasta que entró a la Facultad de Medicina de la UNAM, que entonces se ubicaba en el Centro Histórico, pues antes estudió en un colegio español y vivía en un barrio de puros españoles.<br><br>
Ahora un reconocido psicoanalista, formado también en Estados Unidos.<br><br>
La casa de Enrique es una especie de museo que guarda fotos, libros, vinilos, discos y toda clase de objetos de su familia. En su oficina hay una pared con un enorme retrato de Vicente vestido de militar y de la que cuelgan sus medallas.<br><br>
También guarda un libro de Antoine de Saint-Exupéry, La Terre des Hommes (La Tierra de los Hombres), dedicado por el autor a su padre, a quien conoció en un avión que llevaba correo al Sahara.<br><br>
Para él, la migración es un fenómeno natural de todo ser vivo, empezando por los animales que deben salir de donde habitan y refugiar a otro lugar si el clima es inadecuado o si no hay recursos para vivir bien.<br><br>
“Lo que estamos viendo en este momento tiene que ver con los refugiados que huyen de las economías pobres y de las situaciones desfavorables en búsqueda del lugar donde pueden ser acogidos y donde pueden directamente desarrollarse”, relata.<br><br>
Enrique se refiere a uno de sus libros favoritos, “El Principito”, cuando el protagonista llega a la Tierra y le piden papeles por venir de otro planeta.<br><br>
“El principito se pregunta por qué tenía que tener papeles para vivir en cualquier sitio del mundo. En realidad, el mundo es un planeta y debería de estar liberado de que se le exijan a uno documentos”, termina.<br><br>
