<strong>Queríamos recuperar el tiempo que la vida nos había robado</strong><br><br>
Por Pierre-Marc René<br><br>
Helios Estéves tenía sólo dos meses cuando su padre se fue de la casa a combatir en la Guerra Civil española en 1936. Fue hasta los 19 años, en 1970, que pudo volverlo a ver y conocerlo en Ciudad de México, donde se exilió con miles de otros españoles que huyeron del franquismo. <br><br>
“Vine a México a conocer a mi padre. La ilusión de la familia fue siempre unirnos en algún país. Como en España mi padre no podía regresar porque seguía la dictadura, pues intento yo a los 19 años venir con la ilusión de traer después a mi madre y a mis hermanas. Cuando ya estábamos a punto de conseguirlo, mi padre fallece inesperadamente y los sueños se rompen sin saber si quiera como decírselo mi madre”, cuenta Helios.<br><br>
A sus 83 años y establecido en Guadalajara, el escritor y poeta español no tiene recuerdos directos de la Guerra Civil, pero sí de la dictadura que hizo huir a su padre, que estuvo en el frente de Asturias durante un poco más de un año antes de irse a Francia y luego a México. <br><br>
“Cuando ya el frente lo iban derrotando, mi padre se marchó a Barcelona. Estuvo ahí un año y pico. Luego se pasó a Valencia. Regresó a Barcelona y de ahí finalmente atravesó los Pirineos y llegó a Francia. En Francia estuvo casi dos años esperando quizás que la dictadura no durara, pero eso no sucedió”, relata.<br><br>
Al llegar el último barco que vino a México, el Serpa Pinto, de bandera portuguesa, su padre pudo exiliarse en México en 1942.<br><br>
Su madre la comentó que la despedida en 1936 fue muy difícil.<br><br>
“Mi madre era muy joven, tenía 27 años, yo dos meses, nací en el año 1936 en plena guerra, y me cuenta mi madre que mi padre me agarró en sus brazos y me dio un beso. Mi madre lloraba desconsoladamente, entonces mi padre le dice: ‘Pero mujer, no llores tanto, esta locura no puede durar’, pero ya ves, duró tres años y nunca más se volvieron a ver. A ese beso, yo llegué a México, le traigo ese beso y le hago un poema”, explica.<br><br>
Helios cuenta con mucha emoción el encuentro en México con su padre, en 1970.<br><br>
“Yo traía su foto, él traía la mía y bueno, fue algo que no sé ni expresarlo. Queríamos recuperar el tiempo que la vida nos había robado, hablamos de la vida, del amor, de los porqués, de los silencios del alma. Lloramos juntos, hicimos planes”, recuerda. <br><br>
Tres años vivieron juntos, aunque su padre viajaba mucho. Se veían cada tres o cuatro días, iban al fútbol.<br><br>
“Me duele que mis hermanas no pudieran (escuchar la historia de mi papá), porque sí es doloroso dejar unas hijas como dejó de dos y cuatro años y que nunca más lo volvieron a ver”, confiesa. <br><br>
Cuando falleció su padre, Helios pensó regresarse a España, pero estaba preocupado en quién le iba a ir a dejar flores en su tumba, por lo que se quedó en México.<br><br>
“La vida en México le fue muy difícil. Era un hombre intelectual que no es fácil ganar dinero, y siempre con el dolor del exilio, era un romántico con la esperanza siempre de que la dictadura no podía durar tanto y que se iba a reencontrar con su familia en España. A los casi cuatro años que llegué yo lo alcanza la muerte inesperadamente. Fue dramático”.<br><br>
Para Helios, vivir en México le cambió la perspectiva de las cosas.<br><br>
“En México encuentro un país con más libertades, un país mejor que el que dejo, porque de la guerra España quedó deshecha. Encuentro un país con más luz, con más coches, mujeres conduciendo, me deslumbra bastante la capital de México. Vi más oportunidades para quedarme”, explica.<br><br>
Agradece a México por haber recibido a los españoles con los brazos abiertos, especialmente a los 25 mil exiliados de la guerra, entre ellos a su padre. <br><br>
“Muchos de los exiliados murieron más de esa infinita tristeza que da el exilio, que de las propias enfermedades. Ha sido muy duro para ellos el exilio, aunque aquí vivieron su pequeña República porque México los abrazó y los protegió. De hecho, no hubo relaciones con España hasta la muerte de Franco”.<br><br>
Helios recuerda a su padre como un hombre de bondad, una persona idealista que fundó una escuela en España para ayudar a los que menos tienen.<br><br>
“Quizás el mundo carece de esa gente idealista, política, que sí eran políticos de corazón para hacer sembrar y hacer el bien donde estuvieran”, afirma. <br><br>
Asegura que sólo con el conocimiento y una educación para todos se puede hacer sociedades más igualitarias y más felices.<br><br>
“Mi padre luchó, dio su vida buscando esa igualdad entre las personas, pero que eso solo tenga que ser a través la cultura. Educación, educación y más educación para todos y dar el ejemplo día a día”, concluye. <br><br>
