<strong>Ojalá tengan posibilidades como las tuvimos nosotros </strong><br><br>
Por Pierre-Marc René<br><br><br>
La Guerra Civil en España tiene una presencia importante en la memoria de Lucinda Urrusti. Aunque era apenas una niña, ella y su hermano sabían que algo no andaba bien. <br><br>
Tenía 10 años cuando su familia tuvo que huir de España. Su padre, militar de carrera, sabía que al derrocarse el gobierno republicano habría represalias.<br><br>
“Como mi hermano y yo éramos muy jóvenes, no sentíamos la tragedia. No es que uno no se percatara porque había bombardeos, sonaban las sirenas a cualquier hora y tenías que correr a los refugios. Luego había la lucha de aviones extranjeros. Para mi hermano y para mí era muy bonito verlo. Mi madre se ponía muy nerviosa, ‘métanse dentro’, nos decía, ‘porque esos aviones llevaban ametralladoras’”, recuerda la mujer de 90 años. <br><br>
Cuando Madrid fue cercada, la familia Urrusti tuvo que salir. Lo más fácil era ir a Cataluña, cerca de la frontera con Francia.<br><br>
La familia Urrusti fue trasladada al norte de Francia, pero el padre se quedó en España y no tuvo noticias de él durante mucho tiempo. En Francia, Lucinda y su hermano enviaban cartas a los campos en el sur, donde fueron trasladados los hombres, para saber si su padre había podido cruzar la frontera. <br><br>
“No sabías si tu padre pasó la frontera, si estaba en Francia o si murió en España. En una carta nos contestó que sí estaba en uno de los campos”, comenta. <br><br>
El padre de Lucinda estaba en un campo en la costa sur francesa en condiciones miserables, durmiendo en las playas con los demás hombres exiliados, pero tenía la oportunidad de viajar a Rusia o a México para mantener a su familia a salvo.  <br><br>
Para poder tomar el barco que México ofreció a los exiliados españoles, la familia Urrusti debía ir al puerto de Sète, en el sur del país. No tenían dinero para llegar, pero muchos exiliados se unieron para juntarlo.<br><br>
“Mi madre cosía muy bien y con los trabajos de ella pudimos subsistir. Los que se quedaban nos daban lo poco que tenían para que llegáramos al puerto y no perdernos el barco. Son momentos en que ves lo peor y lo mejor de la humanidad”. <br><br>
Lograron llegar a París, y en la terminal de tren, un francés que hablaba español y que pertenecía al Partido Socialista se percató que la familia era refugiada y se acercó para ayudarlos. <br><br>
“Nos dijo que iba a regresar en la noche con el dinero, nadie creía que iba a cumplir, y resultó que sí. Nos dio francos y pudimos llegar a Sète, reunirnos con mi padre y llegar al puerto donde salía el barco para México”, señala. <br><br>
Para Lucinda, la travesía a México en el Sinaia fue linda y llena de expectativas. En el barco, comían mejor y el gobierno mexicano había preregistrado las personas según sus funciones y profesiones para asignarles una ciudad de acogida una vez en Veracruz. La Ciudad de México fue el destino final de la familia Urrusti. <br><br>
“Nos habían puesto en una bodega, era horrible el calor y era imposible dormir. Mi padre ideó una solución y nos puso en lanchas de salvamento para dormir. Fue fantástico, aunque a las cinco de la mañana pasaban los marineros lavando la cubierta del barco”, cuenta.<br><br>
A Lucinda le pareció que la travesía a México no se iba a acabar nunca, pues duró muchos días y sólo veía cielo y mar, por lo que pensaba que el resto del mundo, fuera de Europa, era así.<br><br>
 “Cuando llegamos a Veracruz me di cuenta que el mundo no era sólo cielo y agua. La llegada a México fue paradisiaca porque el presidente Cárdenas dijo que ese día nadie trabajara y fuera al puerto de Veracruz a recibirnos. Estaba toda Veracruz ahí. Iban con charolas de mangos y de varias cosas. Mi papá, quien estuvo un tiempo en África antes de casarse, ya nos había contado del aguacate, del mango. Empezamos a conocer frutas mexicanas. La llegada a Veracruz fue alucinante”, relata. <br><br>
Por alguna razón que Lucinda no recuerda, la familia Urrusti fue trasladada a la Ciudad de México en ambulancia ya que no tenían otra forma para moverse de Veracruz. <br><br>
“Descubrimos la cuidad y su grandeza. Nos pusieron en un hotel en la calle Guerrero. Así es que empezamos a reconstruir nuestras vidas en México”, comenta. <br><br>
Su padre no pudo ejercer su profesión en México porque por ley hay que ser mexicano de nacimiento para ingresar en el Ejército.<br><br>
"Empezamos el exilio fatal aunque a mi madre le regalaron una máquina de coser y con eso pudimos comer", recuerda.<br><br>
A cumplir sus 18 años, Lucinda y su hermano solicitaron la nacionalidad mexicana. <br><br>
Lucinda estudió hasta la preparatoria en el Colegio Luis Vives, fundada por españoles que llegaron a México. <br><br>
“Tuve maestros formidables. El director del colegio era el señor Landa, que un día me preguntó qué iba a hacer después de la prepa. Me dijo que los maestros le comentaron que tenía talento y facultades para dibujar y me metí a la Escuela de Pintura y Escultura La Esmeralda”, detalla. <br><br>
Hoy Lucinda es reconocida como una de las grandes pintoras de México con una obra calificada de impresionista y abstracta.<br><br>
Tras relatar la historia de su vida, Lucinda reflexiona sobre quienes hoy huyen de sus países y llegan a México: <br><br>
“Hoy me pongo en sus zapatos y me digo: ‘Pobre gente, lo va a pasar mal. Ojalá tengan posibilidades como las que tuvimos nosotros’”, finaliza. <br><br>
